# python main.py --config configs/model/gru4rec_ml1m.yaml
# tmux new -s gru4rec_ml1m 
# --- Model & Dataset ---
model_name: GRU4Rec
dataset_name: ml-1m
seed: 42

window_size: 50

epochs: 200
batch_size: 256
learning_rate: 0.001
weight_decay: 0.0
patience: 20

embedding_dim: 64
hidden_size: 64
num_layers: 1
dropout_prob: 0.2
num_workers: 4

